sudo: required

language: android
jdk: oraclejdk8

notifications:
  email: false

env:
 global:
 - ANDROID_API=27
 - ANDROID_EMULATOR_API=21
 - ANDROID_BUILD_TOOLS=27.0.3

before_install:
  - export TZ=Europe/Berlin
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > "$ANDROID_HOME/licenses/android-sdk-license"
  - yes | sdkmanager "platforms;android-27"
  # Install the rest of tools (e.g., avdmanager).
  #- sdkmanager tools
  # Install the system image.
  #- sdkmanager "system-images;android-${ANDROID_EMULATOR_API};default;armeabi-v7a"
  # Create and start emulator for the script. Meant to race the install task.
  #- echo no | avdmanager create avd --force -n test -k "system-images;android-${ANDROID_EMULATOR_API};default;armeabi-v7a"
  #- $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window &

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache

android:
  components:
    - tools # Update android-sdk (also called android-sdk-tools)
    - platform-tools
    - tools # Write the second time to update to thes newest as described in the document
    - build-tools-${ANDROID_BUILD_TOOLS} # For building
    - android-${ANDROID_API} # For building
    - extra
    - extra-android-m2repository # Support library
#  - sys-img-armeabi-v7a-android-${ANDROID_EMULATOR_API}

  licenses:
  - 'android-sdk-preview-license-52d11cd2'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

#before_script:
#  - android-wait-for-emulator
#  - adb shell settings put global window_animation_scale 0 &
#  - adb shell settings put global transition_animation_scale 0 &
#  - adb shell settings put global animator_duration_scale 0 &
#  - adb shell input keyevent 82 &

script:
  #- ./gradlew clean build connectedCheck -PdisablePreDex --stacktrace
  - ./gradlew clean build -PdisablePreDex --stacktrace